version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    #ports: # some say that if you don't expose your fucking database, you don't even need a firewall
    #  - 27017:27017

  pythonapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  mongodb_data:

